import { dispatchStorage } from './dispatchStorage';
import { schedulerStorage } from './schedulerStorage';
import { storage } from './storage';

export function initializeDispatchData() {
  // Clear existing data for fresh initialization
  const existingDrivers = dispatchStorage.getDrivers();
  const existingTickets = dispatchStorage.getDispatchTickets();
  
  // Only initialize if no data exists
  if (existingDrivers.length > 0 && existingTickets.length > 0) {
    return;
  }

  const drivers = [
    {
      id: 'driver-1',
      name: 'Marcus Hill',
      haulerId: 'hauler-1',
      truckType: 'tri-axle' as const,
      truckCapacity: 18,
      licensePlate: 'NC-8472',
      certifications: ['Clean fill certified', 'DOT certified'],
      performanceScore: 96,
      phone: '(704) 555-0101',
      status: 'available' as const,
      currentLocation: { lat: 35.2271, lng: -80.8431 },
    },
    {
      id: 'driver-2',
      name: 'Sofia Reyes',
      haulerId: 'hauler-2',
      truckType: 'quad-axle' as const,
      truckCapacity: 20,
      licensePlate: 'NC-9203',
      certifications: ['Hazmat', 'DOT certified', 'Heavy haul'],
      performanceScore: 89,
      phone: '(704) 555-0102',
      status: 'on-job' as const,
      currentLocation: { lat: 35.1165, lng: -80.7234 },
    },
    {
      id: 'driver-3',
      name: 'Jordan Lee',
      haulerId: 'hauler-3',
      truckType: 'dump-truck' as const,
      truckCapacity: 15,
      licensePlate: 'NC-5619',
      certifications: ['DOT certified'],
      performanceScore: 73,
      phone: '(704) 555-0103',
      status: 'available' as const,
      currentLocation: { lat: 35.0515, lng: -80.8484 },
    },
    {
      id: 'driver-4',
      name: 'Chen Wu',
      haulerId: 'hauler-4',
      truckType: 'semi-trailer' as const,
      truckCapacity: 25,
      licensePlate: 'NC-2847',
      certifications: ['DOT certified', 'Heavy haul', 'Clean fill certified'],
      performanceScore: 92,
      phone: '(704) 555-0104',
      status: 'available' as const,
      currentLocation: { lat: 35.3074, lng: -80.7307 },
    },
    {
      id: 'driver-5',
      name: 'Isabella Martinez',
      haulerId: 'hauler-1',
      truckType: 'tri-axle' as const,
      truckCapacity: 18,
      licensePlate: 'NC-6739',
      certifications: ['DOT certified', 'Clean fill certified'],
      performanceScore: 88,
      phone: '(704) 555-0105',
      status: 'available' as const,
      currentLocation: { lat: 34.9249, lng: -81.0251 },
    },
    {
      id: 'driver-6',
      name: 'James Thompson',
      haulerId: 'hauler-2',
      truckType: 'quad-axle' as const,
      truckCapacity: 20,
      licensePlate: 'NC-4821',
      certifications: ['Hazmat', 'DOT certified'],
      performanceScore: 79,
      phone: '(704) 555-0106',
      status: 'off-duty' as const,
      currentLocation: { lat: 35.2141, lng: -80.8547 },
    },
    {
      id: 'driver-7',
      name: 'Aisha Patel',
      haulerId: 'hauler-3',
      truckType: 'dump-truck' as const,
      truckCapacity: 16,
      licensePlate: 'NC-9102',
      certifications: ['DOT certified'],
      performanceScore: 94,
      phone: '(704) 555-0107',
      status: 'available' as const,
      currentLocation: { lat: 35.2271, lng: -80.8431 },
    },
    {
      id: 'driver-8',
      name: 'Robert Johnson',
      haulerId: 'hauler-4',
      truckType: 'articulated' as const,
      truckCapacity: 22,
      licensePlate: 'SC-3456',
      certifications: ['DOT certified', 'Heavy haul', 'Clean fill certified'],
      performanceScore: 85,
      phone: '(803) 555-0108',
      status: 'available' as const,
      currentLocation: { lat: 35.1165, lng: -80.7234 },
    },
  ];

  dispatchStorage.setDrivers(drivers);

  const now = new Date();
  const tickets = [
    {
      id: 'T-9001',
      scheduleId: 'DS-5001',
      driverId: 'driver-1',
      haulerCompany: 'Rapid Logistics',
      exportSiteId: 'EX-103',
      importSiteId: 'IM-202',
      volume: 18,
      status: 'delivered' as const,
      createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      acceptedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
      startedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
      loadedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 75 * 60 * 1000).toISOString(),
      deliveredAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 135 * 60 * 1000).toISOString(),
      loadPhotoUrl: 'uploaded',
      unloadPhotoUrl: 'uploaded',
      digitalSignature: 'signature-9001',
      actualVolume: 18,
      customerRating: 5,
      fuelUsed: 8.5,
      gpsTrack: [],
      issues: [],
    },
    {
      id: 'T-9002',
      scheduleId: 'DS-5002',
      driverId: 'driver-2',
      haulerCompany: 'GreenHaul Transport',
      exportSiteId: 'EX-101',
      importSiteId: 'IM-201',
      volume: 20,
      status: 'en-route-delivery' as const,
      createdAt: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
      acceptedAt: new Date(now.getTime() - 3 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
      startedAt: new Date(now.getTime() - 2.5 * 60 * 60 * 1000).toISOString(),
      loadedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
      loadPhotoUrl: 'uploaded',
      customerRating: 4,
      fuelUsed: 10.2,
      gpsTrack: [],
      eta: new Date(now.getTime() + 30 * 60 * 1000).toISOString(),
      issues: [],
    },
    {
      id: 'T-9003',
      scheduleId: 'DS-5003',
      driverId: 'driver-3',
      haulerCompany: 'Budget Movers',
      exportSiteId: 'EX-102',
      importSiteId: 'IM-203',
      volume: 15,
      status: 'delivered' as const,
      createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
      acceptedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
      startedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
      loadedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
      deliveredAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 150 * 60 * 1000).toISOString(),
      loadPhotoUrl: 'uploaded',
      unloadPhotoUrl: 'uploaded',
      customerRating: 3.5,
      fuelUsed: 7.8,
      gpsTrack: [],
      issues: [
        {
          id: 'issue-1',
          type: 'delay' as const,
          description: 'Traffic delay on I-77',
          timestamp: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 100 * 60 * 1000).toISOString(),
          resolved: true,
        },
      ],
    },
    {
      id: 'T-9004',
      scheduleId: 'DS-5001',
      driverId: 'driver-4',
      haulerCompany: 'Premier Fleet',
      exportSiteId: 'EX-101',
      importSiteId: 'IM-202',
      volume: 25,
      status: 'delivered' as const,
      createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      acceptedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
      startedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
      loadedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 70 * 60 * 1000).toISOString(),
      deliveredAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 140 * 60 * 1000).toISOString(),
      loadPhotoUrl: 'uploaded',
      unloadPhotoUrl: 'uploaded',
      digitalSignature: 'signature-9004',
      actualVolume: 25,
      customerRating: 4.5,
      fuelUsed: 12.3,
      gpsTrack: [],
      issues: [],
    },
    {
      id: 'T-9005',
      scheduleId: 'DS-5002',
      driverId: 'driver-5',
      haulerCompany: 'Rapid Logistics',
      exportSiteId: 'EX-103',
      importSiteId: 'IM-201',
      volume: 18,
      status: 'loading' as const,
      createdAt: new Date(now.getTime() - 1 * 60 * 60 * 1000).toISOString(),
      acceptedAt: new Date(now.getTime() - 50 * 60 * 1000).toISOString(),
      startedAt: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
      gpsTrack: [],
      eta: new Date(now.getTime() + 90 * 60 * 1000).toISOString(),
      issues: [],
    },
    {
      id: 'T-9006',
      driverId: 'driver-7',
      haulerCompany: 'Budget Movers',
      exportSiteId: 'EX-101',
      importSiteId: 'IM-203',
      volume: 16,
      status: 'pending' as const,
      createdAt: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
      gpsTrack: [],
      issues: [],
    },
    {
      id: 'T-9007',
      scheduleId: 'DS-5003',
      driverId: 'driver-8',
      haulerCompany: 'Premier Fleet',
      exportSiteId: 'EX-102',
      importSiteId: 'IM-202',
      volume: 22,
      status: 'delivered' as const,
      createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      acceptedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
      startedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
      loadedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 65 * 60 * 1000).toISOString(),
      deliveredAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 125 * 60 * 1000).toISOString(),
      loadPhotoUrl: 'uploaded',
      unloadPhotoUrl: 'uploaded',
      digitalSignature: 'signature-9007',
      actualVolume: 22,
      customerRating: 5,
      fuelUsed: 11.5,
      gpsTrack: [],
      issues: [],
    },
    {
      id: 'T-9008',
      scheduleId: 'DS-5001',
      driverId: 'driver-1',
      haulerCompany: 'Rapid Logistics',
      exportSiteId: 'EX-103',
      importSiteId: 'IM-201',
      volume: 18,
      status: 'delivered' as const,
      createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      acceptedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
      startedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 28 * 60 * 1000).toISOString(),
      loadedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 72 * 60 * 1000).toISOString(),
      deliveredAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 132 * 60 * 1000).toISOString(),
      loadPhotoUrl: 'uploaded',
      unloadPhotoUrl: 'uploaded',
      digitalSignature: 'signature-9008',
      actualVolume: 18,
      customerRating: 4.8,
      fuelUsed: 9.1,
      gpsTrack: [],
      issues: [],
    },
    {
      id: 'T-9009',
      driverId: 'driver-4',
      haulerCompany: 'Premier Fleet',
      exportSiteId: 'EX-101',
      importSiteId: 'IM-203',
      volume: 25,
      status: 'accepted' as const,
      createdAt: new Date(now.getTime() - 10 * 60 * 1000).toISOString(),
      acceptedAt: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
      gpsTrack: [],
      eta: new Date(now.getTime() + 120 * 60 * 1000).toISOString(),
      issues: [],
    },
    {
      id: 'T-9010',
      scheduleId: 'DS-5002',
      driverId: 'driver-7',
      haulerCompany: 'Budget Movers',
      exportSiteId: 'EX-102',
      importSiteId: 'IM-201',
      volume: 16,
      status: 'en-route-pickup' as const,
      createdAt: new Date(now.getTime() - 45 * 60 * 1000).toISOString(),
      acceptedAt: new Date(now.getTime() - 40 * 60 * 1000).toISOString(),
      startedAt: new Date(now.getTime() - 35 * 60 * 1000).toISOString(),
      gpsTrack: [],
      eta: new Date(now.getTime() + 15 * 60 * 1000).toISOString(),
      issues: [],
    },
  ];

  dispatchStorage.setDispatchTickets(tickets);
}
