import { Site, Match } from '@/types/site';
import { Schedule, Hauler } from '@/types/scheduler';
import { GeotechReport } from '@/types/geotechnical';
import { Driver, DispatchTicket } from '@/types/dispatch';
import { storage } from './storage';
import { schedulerStorage } from './schedulerStorage';
import { geotechStorage } from './geotechnicalStorage';
import { dispatchStorage } from './dispatchStorage';
import { initializeComplianceData } from './initComplianceData';
import { initializeOperationsData } from './initOperationsData';

function initializeDriversAndDispatches() {
  // Initialize drivers if none exist
  if (dispatchStorage.getDrivers().length === 0) {
    const drivers: Driver[] = [
      {
        id: 'driver-1',
        name: 'Marcus Hill',
        haulerId: 'hauler-1',
        truckType: 'tri-axle',
        truckCapacity: 18,
        licensePlate: 'NC-8472',
        certifications: ['Clean fill certified', 'DOT certified'],
        performanceScore: 96,
        phone: '(704) 555-0101',
        status: 'available',
        currentLocation: { lat: 35.2271, lng: -80.8431 },
      },
      {
        id: 'driver-2',
        name: 'Sofia Reyes',
        haulerId: 'hauler-2',
        truckType: 'quad-axle',
        truckCapacity: 20,
        licensePlate: 'NC-9203',
        certifications: ['Hazmat', 'DOT certified', 'Heavy haul'],
        performanceScore: 89,
        phone: '(704) 555-0102',
        status: 'on-job',
        currentLocation: { lat: 35.1165, lng: -80.7234 },
      },
      {
        id: 'driver-3',
        name: 'Jordan Lee',
        haulerId: 'hauler-3',
        truckType: 'dump-truck',
        truckCapacity: 15,
        licensePlate: 'NC-5619',
        certifications: ['DOT certified'],
        performanceScore: 73,
        phone: '(704) 555-0103',
        status: 'available',
        currentLocation: { lat: 35.0515, lng: -80.8484 },
      },
      {
        id: 'driver-4',
        name: 'Chen Wu',
        haulerId: 'hauler-4',
        truckType: 'semi-trailer',
        truckCapacity: 25,
        licensePlate: 'NC-2847',
        certifications: ['DOT certified', 'Heavy haul', 'Clean fill certified'],
        performanceScore: 92,
        phone: '(704) 555-0104',
        status: 'available',
        currentLocation: { lat: 35.3074, lng: -80.7307 },
      },
      {
        id: 'driver-5',
        name: 'Isabella Martinez',
        haulerId: 'hauler-1',
        truckType: 'tri-axle',
        truckCapacity: 18,
        licensePlate: 'NC-6739',
        certifications: ['DOT certified', 'Clean fill certified'],
        performanceScore: 88,
        phone: '(704) 555-0105',
        status: 'available',
        currentLocation: { lat: 34.9249, lng: -81.0251 },
      },
      {
        id: 'driver-6',
        name: 'James Thompson',
        haulerId: 'hauler-2',
        truckType: 'quad-axle',
        truckCapacity: 20,
        licensePlate: 'NC-4821',
        certifications: ['Hazmat', 'DOT certified'],
        performanceScore: 79,
        phone: '(704) 555-0106',
        status: 'off-duty',
        currentLocation: { lat: 35.2141, lng: -80.8547 },
      },
      {
        id: 'driver-7',
        name: 'Aisha Patel',
        haulerId: 'hauler-3',
        truckType: 'dump-truck',
        truckCapacity: 16,
        licensePlate: 'NC-9102',
        certifications: ['DOT certified'],
        performanceScore: 94,
        phone: '(704) 555-0107',
        status: 'available',
        currentLocation: { lat: 35.2271, lng: -80.8431 },
      },
      {
        id: 'driver-8',
        name: 'Robert Johnson',
        haulerId: 'hauler-4',
        truckType: 'articulated',
        truckCapacity: 22,
        licensePlate: 'SC-3456',
        certifications: ['DOT certified', 'Heavy haul', 'Clean fill certified'],
        performanceScore: 85,
        phone: '(803) 555-0108',
        status: 'available',
        currentLocation: { lat: 35.1165, lng: -80.7234 },
      },
    ];
    dispatchStorage.setDrivers(drivers);
  }

  // Initialize dispatch tickets if none exist
  if (dispatchStorage.getDispatchTickets().length === 0) {
    const now = new Date();
    const tickets: DispatchTicket[] = [
      {
        id: 'T-9001',
        scheduleId: 'DS-5001',
        driverId: 'driver-1',
        haulerCompany: 'Rapid Logistics',
        exportSiteId: 'EX-103',
        importSiteId: 'IM-202',
        volume: 18,
        status: 'delivered',
        createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 75 * 60 * 1000).toISOString(),
        deliveredAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 135 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        unloadPhotoUrl: 'uploaded',
        digitalSignature: 'signature-9001',
        actualVolume: 18,
        customerRating: 5,
        fuelUsed: 8.5,
        gpsTrack: [],
        issues: [],
      },
      {
        id: 'T-9002',
        scheduleId: 'DS-5002',
        driverId: 'driver-2',
        haulerCompany: 'GreenHaul Transport',
        exportSiteId: 'EX-101',
        importSiteId: 'IM-201',
        volume: 20,
        status: 'en-route-delivery',
        createdAt: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 3 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 2.5 * 60 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        customerRating: 4,
        fuelUsed: 10.2,
        gpsTrack: [],
        eta: new Date(now.getTime() + 30 * 60 * 1000).toISOString(),
        issues: [],
      },
      {
        id: 'T-9003',
        scheduleId: 'DS-5003',
        driverId: 'driver-3',
        haulerCompany: 'Budget Movers',
        exportSiteId: 'EX-102',
        importSiteId: 'IM-203',
        volume: 15,
        status: 'delivered',
        createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
        deliveredAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 150 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        unloadPhotoUrl: 'uploaded',
        customerRating: 3.5,
        fuelUsed: 7.8,
        gpsTrack: [],
        issues: [
          {
            id: 'issue-1',
            type: 'delay',
            description: 'Traffic delay on I-77',
            timestamp: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 100 * 60 * 1000).toISOString(),
            resolved: true,
          },
        ],
      },
      {
        id: 'T-9004',
        scheduleId: 'DS-5001',
        driverId: 'driver-4',
        haulerCompany: 'Premier Fleet',
        exportSiteId: 'EX-101',
        importSiteId: 'IM-202',
        volume: 25,
        status: 'delivered',
        createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 70 * 60 * 1000).toISOString(),
        deliveredAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 140 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        unloadPhotoUrl: 'uploaded',
        digitalSignature: 'signature-9004',
        actualVolume: 25,
        customerRating: 4.5,
        fuelUsed: 12.3,
        gpsTrack: [],
        issues: [],
      },
      {
        id: 'T-9005',
        scheduleId: 'DS-5002',
        driverId: 'driver-5',
        haulerCompany: 'Rapid Logistics',
        exportSiteId: 'EX-103',
        importSiteId: 'IM-201',
        volume: 18,
        status: 'loading',
        createdAt: new Date(now.getTime() - 1 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 50 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
        gpsTrack: [],
        eta: new Date(now.getTime() + 90 * 60 * 1000).toISOString(),
        issues: [],
      },
      {
        id: 'T-9006',
        driverId: 'driver-7',
        haulerCompany: 'Budget Movers',
        exportSiteId: 'EX-101',
        importSiteId: 'IM-203',
        volume: 16,
        status: 'pending',
        createdAt: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
        gpsTrack: [],
        issues: [],
      },
      {
        id: 'T-9007',
        scheduleId: 'DS-5003',
        driverId: 'driver-8',
        haulerCompany: 'Premier Fleet',
        exportSiteId: 'EX-102',
        importSiteId: 'IM-202',
        volume: 22,
        status: 'delivered',
        createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 65 * 60 * 1000).toISOString(),
        deliveredAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 125 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        unloadPhotoUrl: 'uploaded',
        digitalSignature: 'signature-9007',
        actualVolume: 22,
        customerRating: 5,
        fuelUsed: 11.5,
        gpsTrack: [],
        issues: [],
      },
      {
        id: 'T-9008',
        scheduleId: 'DS-5001',
        driverId: 'driver-1',
        haulerCompany: 'Rapid Logistics',
        exportSiteId: 'EX-103',
        importSiteId: 'IM-201',
        volume: 18,
        status: 'delivered',
        createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 28 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 72 * 60 * 1000).toISOString(),
        deliveredAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 132 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        unloadPhotoUrl: 'uploaded',
        digitalSignature: 'signature-9008',
        actualVolume: 18,
        customerRating: 4.8,
        fuelUsed: 9.1,
        gpsTrack: [],
        issues: [],
      },
    ];
    dispatchStorage.setDispatchTickets(tickets);
  }
}


export function initializeSampleData() {
  // Check if data already exists
  const existingSites = storage.getSites();
  const hasInitializedSites = existingSites.length > 0;
  
  if (hasInitializedSites) {
    // Still initialize drivers, dispatches, compliance, and operations even if sites exist
    initializeDriversAndDispatches();
    initializeComplianceData();
    initializeOperationsData();
    return;
  }

  // Sample Export Sites
  const exportSites: Site[] = [
    {
      id: 'EX-101',
      type: 'export',
      name: 'South End Tower Excavation',
      location: '800 South Blvd, Charlotte, NC 28203',
      coordinates: { lat: 35.2141, lng: -80.8547 },
      soilType: 'clay',
      volume: 8500,
      scheduleStart: '2025-02-12',
      scheduleEnd: '2025-03-03',
      contaminated: false,
      priceExpectation: 4,
      projectOwner: 'South End Development LLC',
      status: 'pending',
      createdAt: new Date('2025-02-01').toISOString(),
    },
    {
      id: 'EX-102',
      type: 'export',
      name: 'University District Parking Deck',
      location: '9000 University City Blvd, Charlotte, NC 28223',
      coordinates: { lat: 35.3074, lng: -80.7307 },
      soilType: 'sand',
      volume: 3200,
      scheduleStart: '2025-02-20',
      scheduleEnd: '2025-03-10',
      contaminated: true,
      priceExpectation: 1,
      projectOwner: 'UNCC Facilities',
      status: 'pending',
      createdAt: new Date('2025-02-03').toISOString(),
    },
    {
      id: 'EX-103',
      type: 'export',
      name: 'Monroe Rd Retail Site',
      location: '5200 Monroe Rd, Matthews, NC 28105',
      coordinates: { lat: 35.1165, lng: -80.7234 },
      soilType: 'loam',
      volume: 6000,
      scheduleStart: '2025-02-15',
      scheduleEnd: '2025-02-28',
      contaminated: false,
      priceExpectation: 0,
      projectOwner: 'Matthews Retail Partners',
      status: 'pending',
      createdAt: new Date('2025-02-02').toISOString(),
    },
    {
      id: 'EX-104',
      type: 'export',
      name: 'Uptown Office Complex',
      location: '500 N College St, Charlotte, NC 28202',
      coordinates: { lat: 35.2276, lng: -80.8433 },
      soilType: 'clay',
      volume: 4500,
      scheduleStart: '2025-02-18',
      scheduleEnd: '2025-03-08',
      contaminated: false,
      priceExpectation: 5,
      projectOwner: 'Uptown Properties LLC',
      status: 'pending',
      createdAt: new Date('2025-02-04').toISOString(),
    },
    {
      id: 'EX-105',
      type: 'export',
      name: 'Steele Creek Development',
      location: '12500 Steele Creek Rd, Charlotte, NC 28273',
      coordinates: { lat: 35.1456, lng: -80.9632 },
      soilType: 'loam',
      volume: 7200,
      scheduleStart: '2025-02-22',
      scheduleEnd: '2025-03-15',
      contaminated: false,
      priceExpectation: 3,
      projectOwner: 'Steele Creek Ventures',
      status: 'pending',
      createdAt: new Date('2025-02-05').toISOString(),
    },
  ];

  // Sample Import Sites
  const importSites: Site[] = [
    {
      id: 'IM-201',
      type: 'import',
      name: 'Ballantyne Business Park',
      location: '14825 Ballantyne Corporate Pl, Charlotte, NC 28277',
      coordinates: { lat: 35.0515, lng: -80.8484 },
      soilType: 'clay',
      volume: 4000,
      scheduleStart: '2025-02-18',
      scheduleEnd: '2025-03-05',
      contaminated: false,
      priceExpectation: 6,
      projectOwner: 'Ballantyne Development Corp',
      status: 'pending',
      createdAt: new Date('2025-02-01').toISOString(),
    },
    {
      id: 'IM-202',
      type: 'import',
      name: 'Rock Hill Solar Farm',
      location: '1200 Dave Lyle Blvd, Rock Hill, SC 29730',
      coordinates: { lat: 34.9249, lng: -81.0251 },
      soilType: 'loam',
      volume: 7500,
      scheduleStart: '2025-02-10',
      scheduleEnd: '2025-02-29',
      contaminated: false,
      priceExpectation: 3,
      projectOwner: 'SC Solar Energy LLC',
      status: 'pending',
      createdAt: new Date('2025-02-01').toISOString(),
    },
    {
      id: 'IM-203',
      type: 'import',
      name: 'Uptown Greenway Project',
      location: '220 N Tryon St, Charlotte, NC 28202',
      coordinates: { lat: 35.2271, lng: -80.8431 },
      soilType: 'loam',
      volume: 1800,
      scheduleStart: '2025-02-22',
      scheduleEnd: '2025-03-12',
      contaminated: false,
      priceExpectation: 2,
      projectOwner: 'City of Charlotte Parks',
      status: 'pending',
      createdAt: new Date('2025-02-04').toISOString(),
    },
    {
      id: 'IM-204',
      type: 'import',
      name: 'Fort Mill Industrial Park',
      location: '4500 Highway 21, Fort Mill, SC 29715',
      coordinates: { lat: 35.0076, lng: -80.9451 },
      soilType: 'clay',
      volume: 5200,
      scheduleStart: '2025-02-16',
      scheduleEnd: '2025-03-06',
      contaminated: false,
      priceExpectation: 4,
      projectOwner: 'Fort Mill Commerce Center',
      status: 'pending',
      createdAt: new Date('2025-02-03').toISOString(),
    },
    {
      id: 'IM-205',
      type: 'import',
      name: 'Lake Norman Development',
      location: '18700 Riverfront Dr, Cornelius, NC 28031',
      coordinates: { lat: 35.4876, lng: -80.8789 },
      soilType: 'loam',
      volume: 3600,
      scheduleStart: '2025-02-25',
      scheduleEnd: '2025-03-18',
      contaminated: false,
      priceExpectation: 7,
      projectOwner: 'Lake Norman Builders',
      status: 'pending',
      createdAt: new Date('2025-02-05').toISOString(),
    },
  ];

  // Sample Matches
  const matches: Match[] = [
    {
      id: 'match-103-202',
      exportSiteId: 'EX-103',
      importSiteId: 'IM-202',
      score: 96,
      distance: 17,
      costSavings: 81600,
      carbonReduction: 4080,
      reasons: [
        'Perfect match - clean fill and high volume fit',
        'Excellent proximity for cost efficiency',
        'Perfect soil type match: loam',
        'Volume requirements align well',
        'Clean fill - no contamination concerns',
        'High overall compatibility score',
      ],
      status: 'approved',
      createdAt: new Date('2025-02-05').toISOString(),
    },
    {
      id: 'match-101-201',
      exportSiteId: 'EX-101',
      importSiteId: 'IM-201',
      score: 91,
      distance: 12,
      costSavings: 38400,
      carbonReduction: 1920,
      reasons: [
        'Clay acceptable for structural after compaction',
        'Excellent proximity - minimal haul distance',
        'Perfect soil type match: clay',
        'Volume requirements align well',
        'Clean fill - no contamination concerns',
        'High overall compatibility score',
      ],
      status: 'approved',
      createdAt: new Date('2025-02-05').toISOString(),
    },
    {
      id: 'match-102-203',
      exportSiteId: 'EX-102',
      importSiteId: 'IM-203',
      score: 65,
      distance: 22,
      costSavings: 31680,
      carbonReduction: 1584,
      reasons: [
        'Contamination risk flagged - requires environmental review',
        'Good proximity for cost efficiency',
        'Moderate volume compatibility',
      ],
      status: 'suggested',
      createdAt: new Date('2025-02-05').toISOString(),
    },
    {
      id: 'match-104-204',
      exportSiteId: 'EX-104',
      importSiteId: 'IM-204',
      score: 88,
      distance: 15,
      costSavings: 45200,
      carbonReduction: 2260,
      reasons: [
        'Excellent soil type match: clay',
        'Great volume compatibility',
        'Short haul distance for cost efficiency',
        'Clean fill - no contamination',
      ],
      status: 'suggested',
      createdAt: new Date('2025-02-06').toISOString(),
    },
    {
      id: 'match-105-205',
      exportSiteId: 'EX-105',
      importSiteId: 'IM-205',
      score: 83,
      distance: 19,
      costSavings: 52800,
      carbonReduction: 2640,
      reasons: [
        'Good soil type match: loam',
        'High volume compatibility',
        'Reasonable haul distance',
        'Clean fill material',
      ],
      status: 'suggested',
      createdAt: new Date('2025-02-06').toISOString(),
    },
    {
      id: 'match-104-201',
      exportSiteId: 'EX-104',
      importSiteId: 'IM-201',
      score: 79,
      distance: 14,
      costSavings: 28400,
      carbonReduction: 1420,
      reasons: [
        'Acceptable soil compatibility',
        'Short haul distance',
        'Moderate volume fit',
      ],
      status: 'suggested',
      createdAt: new Date('2025-02-06').toISOString(),
    },
  ];

  // Sample Haulers (additional to existing)
  const additionalHaulers: Hauler[] = [
    {
      id: 'hauler-1',
      name: 'Rapid Logistics',
      reliabilityScore: 96,
      trucksAvailable: 12,
      costPerMile: 3.0,
      status: 'active',
    },
    {
      id: 'hauler-2',
      name: 'GreenHaul Transport',
      reliabilityScore: 92,
      trucksAvailable: 8,
      costPerMile: 3.3,
      status: 'active',
    },
    {
      id: 'hauler-3',
      name: 'Budget Movers',
      reliabilityScore: 85,
      trucksAvailable: 6,
      costPerMile: 2.8,
      status: 'active',
    },
    {
      id: 'hauler-4',
      name: 'Premier Fleet',
      reliabilityScore: 98,
      trucksAvailable: 15,
      costPerMile: 3.5,
      status: 'active',
    },
    {
      id: 'hauler-5',
      name: 'Queen City Hauling',
      reliabilityScore: 94,
      trucksAvailable: 10,
      costPerMile: 3.2,
      status: 'active',
    },
    {
      id: 'hauler-6',
      name: 'Carolina Dirt Movers',
      reliabilityScore: 89,
      trucksAvailable: 7,
      costPerMile: 3.6,
      status: 'active',
    },
  ];

  // Sample Schedules
  const schedules: Schedule[] = [
    {
      id: 'DS-5001',
      matchId: 'match-103-202',
      haulerId: 'hauler-5',
      date: '2025-02-18',
      startTime: '07:00',
      endTime: '15:00',
      route: {
        id: 'route-5001',
        type: 'fastest',
        distance: 17,
        duration: 22.7,
        cost: 54.4,
        carbonEmissions: 13.6,
        waypoints: [
          { lat: 35.1165, lng: -80.7234 },
          { lat: 34.9249, lng: -81.0251 },
        ],
      },
      volumeScheduled: 3000,
      trucksNeeded: 4,
      status: 'scheduled',
      alerts: [],
      weatherDelay: 5,
      trafficDelay: 2,
      createdAt: new Date('2025-02-10').toISOString(),
      isAiGenerated: true,
    },
    {
      id: 'DS-5002',
      matchId: 'match-101-201',
      haulerId: 'hauler-6',
      date: '2025-02-20',
      startTime: '07:00',
      endTime: '14:00',
      route: {
        id: 'route-5002',
        type: 'cheapest',
        distance: 12,
        duration: 16,
        cost: 43.2,
        carbonEmissions: 9.6,
        waypoints: [
          { lat: 35.2141, lng: -80.8547 },
          { lat: 35.0515, lng: -80.8484 },
        ],
      },
      volumeScheduled: 2000,
      trucksNeeded: 3,
      status: 'scheduled',
      alerts: [
        {
          id: 'alert-traffic',
          type: 'traffic',
          severity: 'medium',
          message: 'AM traffic spike - expected 30 min delay',
          timestamp: new Date('2025-02-10').toISOString(),
        },
      ],
      weatherDelay: 62,
      trafficDelay: 30,
      createdAt: new Date('2025-02-10').toISOString(),
      isAiGenerated: true,
    },
    {
      id: 'DS-5003',
      matchId: 'match-102-203',
      haulerId: 'hauler-1',
      date: '2025-02-22',
      startTime: '08:00',
      endTime: '15:00',
      route: {
        id: 'route-5003',
        type: 'greenest',
        distance: 22,
        duration: 29.3,
        cost: 77,
        carbonEmissions: 12.32,
        waypoints: [
          { lat: 35.3074, lng: -80.7307 },
          { lat: 35.2271, lng: -80.8431 },
        ],
      },
      volumeScheduled: 1200,
      trucksNeeded: 2,
      status: 'scheduled',
      alerts: [
        {
          id: 'alert-contamination',
          type: 'conflict',
          severity: 'high',
          message: 'Soil flagged for treatment - requires disposal approval',
          timestamp: new Date('2025-02-10').toISOString(),
        },
      ],
      weatherDelay: 12,
      trafficDelay: 5,
      createdAt: new Date('2025-02-10').toISOString(),
      isAiGenerated: true,
    },
  ];

  schedulerStorage.setSchedules(schedules);

  // Initialize drivers if none exist
  if (dispatchStorage.getDrivers().length === 0) {
    const drivers: Driver[] = [
      {
        id: 'driver-1',
        name: 'Marcus Hill',
        haulerId: 'hauler-1',
        truckType: 'tri-axle',
        truckCapacity: 18,
        licensePlate: 'NC-8472',
        certifications: ['Clean fill certified', 'DOT certified'],
        performanceScore: 96,
        phone: '(704) 555-0101',
        status: 'available',
        currentLocation: { lat: 35.2271, lng: -80.8431 },
      },
      {
        id: 'driver-2',
        name: 'Sofia Reyes',
        haulerId: 'hauler-2',
        truckType: 'quad-axle',
        truckCapacity: 20,
        licensePlate: 'NC-9203',
        certifications: ['Hazmat', 'DOT certified', 'Heavy haul'],
        performanceScore: 89,
        phone: '(704) 555-0102',
        status: 'on-job',
        currentLocation: { lat: 35.1165, lng: -80.7234 },
      },
      {
        id: 'driver-3',
        name: 'Jordan Lee',
        haulerId: 'hauler-3',
        truckType: 'dump-truck',
        truckCapacity: 15,
        licensePlate: 'NC-5619',
        certifications: ['DOT certified'],
        performanceScore: 73,
        phone: '(704) 555-0103',
        status: 'available',
        currentLocation: { lat: 35.0515, lng: -80.8484 },
      },
      {
        id: 'driver-4',
        name: 'Chen Wu',
        haulerId: 'hauler-4',
        truckType: 'semi-trailer',
        truckCapacity: 25,
        licensePlate: 'NC-2847',
        certifications: ['DOT certified', 'Heavy haul', 'Clean fill certified'],
        performanceScore: 92,
        phone: '(704) 555-0104',
        status: 'available',
        currentLocation: { lat: 35.3074, lng: -80.7307 },
      },
      {
        id: 'driver-5',
        name: 'Isabella Martinez',
        haulerId: 'hauler-1',
        truckType: 'tri-axle',
        truckCapacity: 18,
        licensePlate: 'NC-6739',
        certifications: ['DOT certified', 'Clean fill certified'],
        performanceScore: 88,
        phone: '(704) 555-0105',
        status: 'available',
        currentLocation: { lat: 34.9249, lng: -81.0251 },
      },
      {
        id: 'driver-6',
        name: 'James Thompson',
        haulerId: 'hauler-2',
        truckType: 'quad-axle',
        truckCapacity: 20,
        licensePlate: 'NC-4821',
        certifications: ['Hazmat', 'DOT certified'],
        performanceScore: 79,
        phone: '(704) 555-0106',
        status: 'off-duty',
        currentLocation: { lat: 35.2141, lng: -80.8547 },
      },
      {
        id: 'driver-7',
        name: 'Aisha Patel',
        haulerId: 'hauler-3',
        truckType: 'dump-truck',
        truckCapacity: 16,
        licensePlate: 'NC-9102',
        certifications: ['DOT certified'],
        performanceScore: 94,
        phone: '(704) 555-0107',
        status: 'available',
        currentLocation: { lat: 35.2271, lng: -80.8431 },
      },
      {
        id: 'driver-8',
        name: 'Robert Johnson',
        haulerId: 'hauler-4',
        truckType: 'articulated',
        truckCapacity: 22,
        licensePlate: 'SC-3456',
        certifications: ['DOT certified', 'Heavy haul', 'Clean fill certified'],
        performanceScore: 85,
        phone: '(803) 555-0108',
        status: 'available',
        currentLocation: { lat: 35.1165, lng: -80.7234 },
      },
    ];
    dispatchStorage.setDrivers(drivers);
  }

  // Initialize dispatch tickets if none exist
  if (dispatchStorage.getDispatchTickets().length === 0) {
    const now = new Date();
    const tickets: DispatchTicket[] = [
      {
        id: 'T-9001',
        scheduleId: 'DS-5001',
        driverId: 'driver-1',
        haulerCompany: 'Rapid Logistics',
        exportSiteId: 'EX-103',
        importSiteId: 'IM-202',
        volume: 18,
        status: 'delivered',
        createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 75 * 60 * 1000).toISOString(),
        deliveredAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000 + 135 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        unloadPhotoUrl: 'uploaded',
        digitalSignature: 'signature-9001',
        actualVolume: 18,
        customerRating: 5,
        fuelUsed: 8.5,
        gpsTrack: [],
        issues: [],
      },
      {
        id: 'T-9002',
        scheduleId: 'DS-5002',
        driverId: 'driver-2',
        haulerCompany: 'GreenHaul Transport',
        exportSiteId: 'EX-101',
        importSiteId: 'IM-201',
        volume: 20,
        status: 'en-route-delivery',
        createdAt: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 3 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 2.5 * 60 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        customerRating: 4,
        fuelUsed: 10.2,
        gpsTrack: [],
        eta: new Date(now.getTime() + 30 * 60 * 1000).toISOString(),
        issues: [],
      },
      {
        id: 'T-9003',
        scheduleId: 'DS-5003',
        driverId: 'driver-3',
        haulerCompany: 'Budget Movers',
        exportSiteId: 'EX-102',
        importSiteId: 'IM-203',
        volume: 15,
        status: 'delivered',
        createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
        deliveredAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 150 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        unloadPhotoUrl: 'uploaded',
        customerRating: 3.5,
        fuelUsed: 7.8,
        gpsTrack: [],
        issues: [
          {
            id: 'issue-1',
            type: 'delay',
            description: 'Traffic delay on I-77',
            timestamp: new Date(now.getTime() - 24 * 60 * 60 * 1000 + 100 * 60 * 1000).toISOString(),
            resolved: true,
          },
        ],
      },
      {
        id: 'T-9004',
        scheduleId: 'DS-5001',
        driverId: 'driver-4',
        haulerCompany: 'Premier Fleet',
        exportSiteId: 'EX-101',
        importSiteId: 'IM-202',
        volume: 25,
        status: 'delivered',
        createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 70 * 60 * 1000).toISOString(),
        deliveredAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 140 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        unloadPhotoUrl: 'uploaded',
        digitalSignature: 'signature-9004',
        actualVolume: 25,
        customerRating: 4.5,
        fuelUsed: 12.3,
        gpsTrack: [],
        issues: [],
      },
      {
        id: 'T-9005',
        scheduleId: 'DS-5002',
        driverId: 'driver-5',
        haulerCompany: 'Rapid Logistics',
        exportSiteId: 'EX-103',
        importSiteId: 'IM-201',
        volume: 18,
        status: 'loading',
        createdAt: new Date(now.getTime() - 1 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 50 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
        gpsTrack: [],
        eta: new Date(now.getTime() + 90 * 60 * 1000).toISOString(),
        issues: [],
      },
      {
        id: 'T-9006',
        driverId: 'driver-7',
        haulerCompany: 'Budget Movers',
        exportSiteId: 'EX-101',
        importSiteId: 'IM-203',
        volume: 16,
        status: 'pending',
        createdAt: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
        gpsTrack: [],
        issues: [],
      },
      {
        id: 'T-9007',
        scheduleId: 'DS-5003',
        driverId: 'driver-8',
        haulerCompany: 'Premier Fleet',
        exportSiteId: 'EX-102',
        importSiteId: 'IM-202',
        volume: 22,
        status: 'delivered',
        createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 65 * 60 * 1000).toISOString(),
        deliveredAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000 + 125 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        unloadPhotoUrl: 'uploaded',
        digitalSignature: 'signature-9007',
        actualVolume: 22,
        customerRating: 5,
        fuelUsed: 11.5,
        gpsTrack: [],
        issues: [],
      },
      {
        id: 'T-9008',
        scheduleId: 'DS-5001',
        driverId: 'driver-1',
        haulerCompany: 'Rapid Logistics',
        exportSiteId: 'EX-103',
        importSiteId: 'IM-201',
        volume: 18,
        status: 'delivered',
        createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        acceptedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
        startedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 28 * 60 * 1000).toISOString(),
        loadedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 72 * 60 * 1000).toISOString(),
        deliveredAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000 + 132 * 60 * 1000).toISOString(),
        loadPhotoUrl: 'uploaded',
        unloadPhotoUrl: 'uploaded',
        digitalSignature: 'signature-9008',
        actualVolume: 18,
        customerRating: 4.8,
        fuelUsed: 9.1,
        gpsTrack: [],
        issues: [],
      },
    ];
    dispatchStorage.setDispatchTickets(tickets);
  }

  // Sample Geotechnical Reports
  const reports: GeotechReport[] = [
    {
      id: 'GT-001',
      name: 'South End Tower - Clay Analysis',
      siteId: 'EX-101',
      uploadDate: new Date('2025-02-01').toISOString(),
      fileType: 'pdf',
      classification: 'structural-fill',
      suitabilityScore: 84,
      properties: {
        moistureContent: 18,
        compaction: 92,
        density: 123,
        pH: 7.1,
        organicContent: 1.2,
        grainSize: {
          clay: 45,
          silt: 35,
          sand: 20,
        },
        contaminants: [],
      },
      aiExtracted: true,
      reuseRecommendations: [
        'Excellent for foundation support and load-bearing applications',
        'Suitable for highway embankments and retaining wall backfill',
        'Can be used for critical infrastructure projects',
        'High compaction rate ideal for immediate structural use',
      ],
      riskFactors: [],
      treatmentOptions: [],
      location: 'South End, Charlotte, NC',
      testDate: '2025-01-28',
      laboratory: 'Terracon Consultants',
      notes: 'CL Clay - No organic matter detected. Meets NCDOT specifications.',
    },
    {
      id: 'GT-002',
      name: 'University District - Sandy Loam Report',
      siteId: 'EX-102',
      uploadDate: new Date('2025-02-03').toISOString(),
      fileType: 'pdf',
      classification: 'general-fill',
      suitabilityScore: 52,
      properties: {
        moistureContent: 12,
        compaction: 86,
        density: 115,
        pH: 6.8,
        organicContent: 2.5,
        grainSize: {
          sand: 55,
          silt: 30,
          clay: 15,
        },
        contaminants: ['Lead'],
      },
      aiExtracted: true,
      reuseRecommendations: [
        'Acceptable for non-structural fills and mass grading',
        'May be suitable for landscaping after amendment',
      ],
      riskFactors: [
        'Contains hazardous materials - handle with care',
        'May require special handling and disposal permits',
        'Low compaction - may not meet project specifications',
      ],
      treatmentOptions: [
        'Professional remediation required',
        'Consider soil washing or thermal treatment',
        'Recompaction required with proper moisture control',
      ],
      location: 'University City, Charlotte, NC',
      testDate: '2025-02-01',
      laboratory: 'Environmental Testing Services',
      notes: 'SM Sandy Loam - Low lead detected (35 ppm). Treated but requires disposal approval.',
    },
    {
      id: 'GT-003',
      name: 'Monroe Road - General Fill Assessment',
      siteId: 'EX-103',
      uploadDate: new Date('2025-02-02').toISOString(),
      fileType: 'pdf',
      classification: 'select-fill',
      suitabilityScore: 63,
      properties: {
        moistureContent: 10,
        compaction: 78,
        density: 108,
        pH: 7.3,
        organicContent: 4.1,
        grainSize: {
          sand: 40,
          silt: 35,
          clay: 25,
        },
        contaminants: [],
      },
      aiExtracted: true,
      reuseRecommendations: [
        'Suitable for general backfill and grading projects',
        'Good for utility trench backfill',
        'Can be used for landscape grading and site preparation',
        'Low moisture content ideal for immediate placement',
      ],
      riskFactors: [
        'Low compaction - may not meet project specifications',
        'Organic content may decompose and cause settlement',
      ],
      treatmentOptions: [
        'Recompaction required with proper moisture control',
        'Remove organic material or stabilize with additives',
      ],
      location: 'Matthews, NC',
      testDate: '2025-01-30',
      laboratory: 'Geotechnical Solutions Inc',
      notes: 'General fill dirt - Clean material suitable for landscaping or general backfill.',
    },
    {
      id: 'GT-004',
      name: 'Rock Hill Test Pit - Sandy Clay',
      uploadDate: new Date('2025-02-01').toISOString(),
      fileType: 'pdf',
      classification: 'select-fill',
      suitabilityScore: 71,
      properties: {
        moistureContent: 22,
        compaction: 88,
        density: 118,
        pH: 7.0,
        organicContent: 1.8,
        grainSize: {
          sand: 50,
          clay: 30,
          silt: 20,
        },
        contaminants: [],
      },
      aiExtracted: true,
      reuseRecommendations: [
        'Suitable for general backfill and grading projects',
        'Good for utility trench backfill',
        'Can be used for landscape grading and site preparation',
      ],
      riskFactors: [
        'High moisture content may require drying time',
      ],
      treatmentOptions: [
        'Allow material to dry or use moisture conditioning',
      ],
      location: 'Rock Hill, SC',
      testDate: '2025-01-25',
      laboratory: 'Carolina Geotechnical',
      notes: 'SC Sandy Clay - Suitable after drying. Good material for general use.',
    },
  ];

  // Initialize data
  storage.setSites([...exportSites, ...importSites]);
  storage.setMatches(matches);
  
  const existingHaulers = schedulerStorage.getHaulers();
  schedulerStorage.setHaulers([...existingHaulers, ...additionalHaulers]);
  schedulerStorage.setSchedules(schedules);
  
  geotechStorage.setReports(reports);

  // Update matched sites status
  const allSites = [...exportSites, ...importSites];
  const updatedSites = allSites.map(site => {
    const hasMatch = matches.find(m => 
      (m.exportSiteId === site.id || m.importSiteId === site.id) && 
      m.status === 'approved'
    );
    return hasMatch ? { ...site, status: 'matched' as const } : site;
  });
  storage.setSites(updatedSites);
  
  // Initialize drivers and dispatch tickets
  initializeDriversAndDispatches();
  
  // Initialize compliance data
  initializeComplianceData();
  
  // Initialize operations data
  initializeOperationsData();
}
