import { Permit } from '@/types/municipality';
import { Lead } from '@/types/lead';
import { MunicipalityIntegration } from '@/types/municipality';
import { municipalityStorage } from './municipalityStorage';
import { leadStorage } from './leadStorage';

export function initializePermitData() {
  // Only initialize if no permits exist yet (allows sample data on fresh sessions)
  const existingPermits = municipalityStorage.getPermits();
  const existingLeads = leadStorage.getLeads();
  
  // Always refresh leads if we have less than 10 (ensures new sample leads are added)
  const needsLeadRefresh = existingLeads.length < 10;
  
  if (existingPermits.length > 0 && !needsLeadRefresh) {
    return;
  }

  // Create municipality integrations
  const integrations: MunicipalityIntegration[] = [
    {
      id: 'int-durham',
      city: 'Durham',
      state: 'NC',
      apiBaseUrl: 'https://api.durhamnc.gov/permits',
      authType: 'api_key',
      apiKey: '••••••••',
      syncFrequency: 'daily',
      status: 'active',
      isActive: true,
      lastSyncTime: new Date().toISOString(),
      lastSyncResult: '12 created, 3 updated',
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'int-raleigh',
      city: 'Raleigh',
      state: 'NC',
      apiBaseUrl: 'https://api.raleighnc.gov/permits',
      authType: 'api_key',
      apiKey: '••••••••',
      syncFrequency: 'daily',
      status: 'active',
      isActive: true,
      lastSyncTime: new Date().toISOString(),
      lastSyncResult: '8 created, 2 updated',
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  // Durham Permits
  const durhamPermits: Permit[] = [
    {
      id: 'pmt-dur-001',
      externalPermitId: 'DUR-2024-00891',
      municipalityId: 'int-durham',
      projectName: 'Durham Bulls Athletic Park Expansion',
      projectType: 'Mixed Use',
      status: 'Approved',
      address: '409 Blackwell St',
      city: 'Durham',
      state: 'NC',
      zip: '27701',
      contractorName: 'Edifice Construction',
      contactEmail: 'permits@edificeconstruction.com',
      contactPhone: '(919) 555-1234',
      estimatedStartDate: '2024-02-15',
      description: 'Mixed-use expansion near DBAP with retail and residential. Significant underground parking excavation required.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-dur-002',
      externalPermitId: 'DUR-2024-00923',
      municipalityId: 'int-durham',
      projectName: 'American Tobacco Campus Phase 4',
      projectType: 'Commercial',
      status: 'Issued',
      address: '318 Blackwell St',
      city: 'Durham',
      state: 'NC',
      zip: '27701',
      contractorName: 'Barnhill Contracting',
      contactEmail: 'info@barnhill.com',
      contactPhone: '(919) 555-2345',
      estimatedStartDate: '2024-01-20',
      description: 'Commercial office and entertainment complex. Site grading and foundation work.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-dur-003',
      externalPermitId: 'DUR-2024-00945',
      municipalityId: 'int-durham',
      projectName: 'Brightleaf District Office Tower',
      projectType: 'Commercial',
      status: 'Approved',
      address: '905 W Main St',
      city: 'Durham',
      state: 'NC',
      zip: '27701',
      contractorName: 'Balfour Beatty',
      contactEmail: 'durham@balfourbeattyus.com',
      contactPhone: '(919) 555-3456',
      estimatedStartDate: '2024-03-01',
      description: '6-story Class A office building with structured parking. Extensive site preparation and grading.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-dur-004',
      externalPermitId: 'DUR-2024-00967',
      municipalityId: 'int-durham',
      projectName: 'Duke University West Campus Housing',
      projectType: 'Residential',
      status: 'Under Review',
      address: '200 Science Dr',
      city: 'Durham',
      state: 'NC',
      zip: '27708',
      contractorName: 'Choate Construction',
      contactEmail: 'bids@choateco.com',
      contactPhone: '(919) 555-4567',
      estimatedStartDate: '2024-04-15',
      description: '8-story student housing near Duke University. Foundation and underground utilities work.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-dur-005',
      externalPermitId: 'DUR-2024-00989',
      municipalityId: 'int-durham',
      projectName: 'Downtown Durham Hotel & Conference Center',
      projectType: 'Commercial',
      status: 'Approved',
      address: '215 N Church St',
      city: 'Durham',
      state: 'NC',
      zip: '27701',
      contractorName: 'Holder Construction',
      contactEmail: 'southeast@holderconstruction.com',
      contactPhone: '(919) 555-5678',
      estimatedStartDate: '2024-02-01',
      description: '18-story luxury hotel with 350 rooms and conference space. Deep foundation excavation.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-dur-006',
      externalPermitId: 'DUR-2024-01012',
      municipalityId: 'int-durham',
      projectName: 'RTP Distribution Center',
      projectType: 'Industrial',
      status: 'Issued',
      address: '4000 S Miami Blvd',
      city: 'Durham',
      state: 'NC',
      zip: '27703',
      contractorName: 'Clayco',
      contactEmail: 'durham@clayco.com',
      contactPhone: '(919) 555-6789',
      estimatedStartDate: '2024-01-10',
      description: '750,000 SF distribution warehouse. Major site clearing and grading on 65-acre parcel.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-dur-007',
      externalPermitId: 'DUR-2024-01034',
      municipalityId: 'int-durham',
      projectName: 'Ninth Street Retail Renovation',
      projectType: 'Commercial',
      status: 'Approved',
      address: '750 Ninth St',
      city: 'Durham',
      state: 'NC',
      zip: '27705',
      contractorName: 'Little Diversified',
      contactEmail: 'projects@littleonline.com',
      contactPhone: '(919) 555-7890',
      estimatedStartDate: '2024-03-15',
      description: 'Renovation of retail building with new outdoor plaza. Minor excavation for utilities.',
      estimatedEarthworkFlag: 'unknown',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-dur-008',
      externalPermitId: 'DUR-2024-01056',
      municipalityId: 'int-durham',
      projectName: 'Durham Innovation District Phase 3',
      projectType: 'Mixed Use',
      status: 'Issued',
      address: '500 Foster St',
      city: 'Durham',
      state: 'NC',
      zip: '27701',
      contractorName: 'Rodgers Builders',
      contactEmail: 'info@rodgersbuilders.com',
      contactPhone: '(919) 555-8901',
      estimatedStartDate: '2024-01-25',
      description: 'Mixed-use development in Durham innovation corridor. Site work and new foundations.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
  ];

  // Raleigh Permits
  const raleighPermits: Permit[] = [
    {
      id: 'pmt-ral-001',
      externalPermitId: 'RAL-2024-00456',
      municipalityId: 'int-raleigh',
      projectName: 'Downtown Raleigh Innovation District',
      projectType: 'Mixed Use',
      status: 'Approved',
      address: '300 S Wilmington St',
      city: 'Raleigh',
      state: 'NC',
      zip: '27601',
      contractorName: 'Skanska USA',
      contactEmail: 'raleigh@skanska.com',
      contactPhone: '(919) 555-1234',
      estimatedStartDate: '2024-02-20',
      description: '25-story mixed-use development with tech office space, retail, and residential. Major excavation for 4-level parking deck.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-002',
      externalPermitId: 'RAL-2024-00478',
      municipalityId: 'int-raleigh',
      projectName: 'North Hills Tower III',
      projectType: 'Commercial',
      status: 'Issued',
      address: '4600 Six Forks Rd',
      city: 'Raleigh',
      state: 'NC',
      zip: '27609',
      contractorName: 'Brasfield & Gorrie',
      contactEmail: 'info@brasfieldgorrie.com',
      contactPhone: '(919) 555-2345',
      estimatedStartDate: '2024-01-15',
      description: '16-story Class A office tower in North Hills district. Structured parking and site grading.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-003',
      externalPermitId: 'RAL-2024-00501',
      municipalityId: 'int-raleigh',
      projectName: 'Warehouse District Apartments',
      projectType: 'Residential',
      status: 'Approved',
      address: '500 W Martin St',
      city: 'Raleigh',
      state: 'NC',
      zip: '27603',
      contractorName: 'Clancy & Theys',
      contactEmail: 'raleigh@clancytheys.com',
      contactPhone: '(919) 555-3456',
      estimatedStartDate: '2024-03-10',
      description: '320-unit luxury apartment complex with courtyard amenities. Foundation and underground parking excavation.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-004',
      externalPermitId: 'RAL-2024-00523',
      municipalityId: 'int-raleigh',
      projectName: 'Research Triangle Park Lab Campus',
      projectType: 'Commercial',
      status: 'Issued',
      address: '1000 Park Dr',
      city: 'Raleigh',
      state: 'NC',
      zip: '27709',
      contractorName: 'Turner Construction',
      contactEmail: 'rtp@tcco.com',
      contactPhone: '(919) 555-4567',
      estimatedStartDate: '2024-01-05',
      description: 'Bio-pharma research campus with 3 laboratory buildings. Extensive site work on 40-acre greenfield site.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-005',
      externalPermitId: 'RAL-2024-00545',
      municipalityId: 'int-raleigh',
      projectName: 'Glenwood South Hotel',
      projectType: 'Commercial',
      status: 'Under Review',
      address: '600 Glenwood Ave',
      city: 'Raleigh',
      state: 'NC',
      zip: '27603',
      contractorName: 'Samet Corporation',
      contactEmail: 'projects@sametcorp.com',
      contactPhone: '(919) 555-5678',
      estimatedStartDate: '2024-04-01',
      description: 'Boutique hotel with rooftop restaurant and event space. Foundation work in urban infill location.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-006',
      externalPermitId: 'RAL-2024-00567',
      municipalityId: 'int-raleigh',
      projectName: 'Wake Forest Road Medical Center',
      projectType: 'Infrastructure',
      status: 'Approved',
      address: '3000 Wake Forest Rd',
      city: 'Raleigh',
      state: 'NC',
      zip: '27609',
      contractorName: 'Robins & Morton',
      contactEmail: 'healthcare@robinsmorton.com',
      contactPhone: '(919) 555-6789',
      estimatedStartDate: '2024-02-28',
      description: '150,000 SF outpatient medical facility. Site preparation and utility infrastructure.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-007',
      externalPermitId: 'RAL-2024-00589',
      municipalityId: 'int-raleigh',
      projectName: 'Crabtree Valley Mall Expansion',
      projectType: 'Commercial',
      status: 'Approved',
      address: '4325 Glenwood Ave',
      city: 'Raleigh',
      state: 'NC',
      zip: '27612',
      contractorName: 'JE Dunn Construction',
      contactEmail: 'raleigh@jedunn.com',
      contactPhone: '(919) 555-7890',
      estimatedStartDate: '2024-03-20',
      description: 'Mall expansion with new anchor store and parking structure. Demolition and site preparation.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-008',
      externalPermitId: 'RAL-2024-00612',
      municipalityId: 'int-raleigh',
      projectName: 'Hillsborough Street Student Housing',
      projectType: 'Residential',
      status: 'Issued',
      address: '2800 Hillsborough St',
      city: 'Raleigh',
      state: 'NC',
      zip: '27607',
      contractorName: 'Landmark Properties',
      contactEmail: 'construction@landmarkproperties.com',
      contactPhone: '(919) 555-8901',
      estimatedStartDate: '2024-01-30',
      description: '450-bed student housing near NC State. Foundation and underground utilities.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
  ];

  const allPermits = [...durhamPermits, ...raleighPermits];

  // Create some leads from existing permits
  const sampleLeads: Lead[] = [
    {
      id: 'lead-001',
      permitId: 'pmt-dur-001',
      projectName: 'Durham Bulls Athletic Park Expansion',
      contractorName: 'Edifice Construction',
      contactEmail: 'permits@edificeconstruction.com',
      contactPhone: '(919) 555-1234',
      city: 'Durham',
      state: 'NC',
      address: '409 Blackwell St',
      description: 'Mixed-use expansion - high volume earthwork opportunity',
      leadOwner: 'Sarah Johnson',
      leadStatus: 'converted_to_job',
      jobId: 'J-3001',
      notes: 'Won contract. 45,000 CY export over 6 months. Starting Feb 15.',
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-002',
      permitId: 'pmt-dur-006',
      projectName: 'RTP Distribution Center',
      contractorName: 'Clayco',
      contactEmail: 'durham@clayco.com',
      contactPhone: '(919) 555-6789',
      city: 'Durham',
      state: 'NC',
      address: '4000 S Miami Blvd',
      description: '750,000 SF distribution warehouse - major grading project',
      leadOwner: 'Mike Chen',
      leadStatus: 'converted_to_job',
      jobId: 'J-3002',
      notes: 'Contract signed. 65,000 CY grading project. Mobilization next week.',
      createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-003',
      permitId: 'pmt-ral-001',
      projectName: 'Downtown Raleigh Innovation District',
      contractorName: 'Skanska USA',
      contactEmail: 'raleigh@skanska.com',
      contactPhone: '(919) 555-1234',
      city: 'Raleigh',
      state: 'NC',
      address: '300 S Wilmington St',
      description: '25-story development with 4-level parking excavation',
      leadOwner: 'Emily Rodriguez',
      leadStatus: 'qualified',
      notes: 'High priority - flagship downtown project. Final bid due Feb 20.',
      createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-004',
      permitId: 'pmt-ral-004',
      projectName: 'Research Triangle Park Lab Campus',
      contractorName: 'Turner Construction',
      contactEmail: 'rtp@tcco.com',
      contactPhone: '(919) 555-4567',
      city: 'Raleigh',
      state: 'NC',
      address: '1000 Park Dr',
      description: 'Bio-pharma campus - 40-acre greenfield site work',
      leadOwner: 'David Kim',
      leadStatus: 'converted_to_job',
      jobId: 'J-3003',
      notes: 'Won RFP! 80,000 CY combined import/export. Multi-phase project.',
      createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-005',
      permitId: 'pmt-dur-008',
      projectName: 'Durham Innovation District Phase 3',
      contractorName: 'Rodgers Builders',
      contactEmail: 'info@rodgersbuilders.com',
      contactPhone: '(919) 555-8901',
      city: 'Durham',
      state: 'NC',
      address: '500 Foster St',
      description: 'Innovation corridor development - site work and foundations',
      leadOwner: 'Sarah Johnson',
      leadStatus: 'contacted',
      notes: 'Spoke with PM. Need to coordinate with historic preservation requirements.',
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-006',
      permitId: 'pmt-dur-002',
      projectName: 'American Tobacco Campus Phase 4',
      contractorName: 'Barnhill Contracting',
      contactEmail: 'info@barnhill.com',
      contactPhone: '(919) 555-2345',
      city: 'Durham',
      state: 'NC',
      address: '318 Blackwell St',
      description: 'Commercial office complex - site grading and foundation work',
      leadOwner: 'Mike Chen',
      leadStatus: 'qualified',
      notes: 'Pre-bid meeting attended. Strong relationship with contractor.',
      createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-007',
      permitId: 'pmt-dur-003',
      projectName: 'Brightleaf District Office Tower',
      contractorName: 'Balfour Beatty',
      contactEmail: 'durham@balfourbeattyus.com',
      contactPhone: '(919) 555-3456',
      city: 'Durham',
      state: 'NC',
      address: '905 W Main St',
      description: '6-story Class A office with structured parking',
      leadOwner: 'Emily Rodriguez',
      leadStatus: 'new',
      notes: 'Just created from permit sync. High-value corporate client.',
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-008',
      permitId: 'pmt-ral-002',
      projectName: 'North Hills Tower III',
      contractorName: 'Brasfield & Gorrie',
      contactEmail: 'nc@brasfieldgorrie.com',
      contactPhone: '(919) 555-2345',
      city: 'Raleigh',
      state: 'NC',
      address: '4600 Six Forks Rd',
      description: '16-story Class A office tower',
      leadOwner: 'David Kim',
      leadStatus: 'disqualified',
      notes: 'Lost to competitor - price too high. Keep relationship warm.',
      createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-009',
      permitId: 'pmt-ral-006',
      projectName: 'Wake Forest Road Medical Center',
      contractorName: 'Robins & Morton',
      contactEmail: 'healthcare@robinsmorton.com',
      contactPhone: '(919) 555-6789',
      city: 'Raleigh',
      state: 'NC',
      address: '3000 Wake Forest Rd',
      description: 'Outpatient medical facility - site preparation',
      leadOwner: 'Sarah Johnson',
      leadStatus: 'converted_to_job',
      jobId: 'J-3004',
      notes: 'Contract executed. Starting earthwork March 1.',
      createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-010',
      permitId: 'pmt-dur-004',
      projectName: 'Duke University West Campus Housing',
      contractorName: 'Choate Construction',
      contactEmail: 'bids@choateco.com',
      contactPhone: '(919) 555-4567',
      city: 'Durham',
      state: 'NC',
      address: '200 Science Dr',
      description: '8-story student housing near Duke University',
      leadOwner: 'Mike Chen',
      leadStatus: 'contacted',
      notes: 'Initial outreach sent. Meeting scheduled for Thursday.',
      createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-011',
      permitId: 'pmt-ral-008',
      projectName: 'Hillsborough Street Student Housing',
      contractorName: 'Landmark Properties',
      contactEmail: 'construction@landmarkproperties.com',
      contactPhone: '(919) 555-8901',
      city: 'Raleigh',
      state: 'NC',
      address: '2800 Hillsborough St',
      description: '450-bed student housing near NC State campus',
      leadOwner: 'Emily Rodriguez',
      leadStatus: 'new',
      notes: 'High volume potential. Student housing specialist.',
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-012',
      permitId: 'pmt-dur-005',
      projectName: 'Downtown Durham Hotel & Conference Center',
      contractorName: 'Holder Construction',
      contactEmail: 'southeast@holderconstruction.com',
      contactPhone: '(919) 555-5678',
      city: 'Durham',
      state: 'NC',
      address: '215 N Church St',
      description: '18-story luxury hotel - critical infrastructure',
      leadOwner: 'David Kim',
      leadStatus: 'qualified',
      notes: 'Specialized requirements. Need to confirm clean fill specs.',
      createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];

  // Save to storage
  municipalityStorage.setIntegrations(integrations);
  municipalityStorage.setPermits(allPermits);
  leadStorage.setLeads(sampleLeads);
}
