import { Permit } from '@/types/municipality';
import { Lead } from '@/types/lead';
import { MunicipalityIntegration } from '@/types/municipality';
import { municipalityStorage } from './municipalityStorage';
import { leadStorage } from './leadStorage';

export function initializePermitData() {
  // Only initialize if no permits exist yet (allows sample data on fresh sessions)
  const existingPermits = municipalityStorage.getPermits();
  if (existingPermits.length > 0) {
    return;
  }

  // Create municipality integrations
  const integrations: MunicipalityIntegration[] = [
    {
      id: 'int-charlotte',
      city: 'Charlotte',
      state: 'NC',
      apiBaseUrl: 'https://api.charlottenc.gov/permits',
      authType: 'api_key',
      apiKey: '••••••••',
      syncFrequency: 'daily',
      status: 'active',
      isActive: true,
      lastSyncTime: new Date().toISOString(),
      lastSyncResult: '12 created, 3 updated',
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'int-raleigh',
      city: 'Raleigh',
      state: 'NC',
      apiBaseUrl: 'https://api.raleighnc.gov/permits',
      authType: 'api_key',
      apiKey: '••••••••',
      syncFrequency: 'daily',
      status: 'active',
      isActive: true,
      lastSyncTime: new Date().toISOString(),
      lastSyncResult: '8 created, 2 updated',
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  // Charlotte Permits
  const charlottePermits: Permit[] = [
    {
      id: 'pmt-clt-001',
      externalPermitId: 'CLT-2024-00891',
      municipalityId: 'int-charlotte',
      projectName: 'South End Mixed-Use Development',
      projectType: 'Mixed Use',
      status: 'Approved',
      address: '2100 South Blvd',
      city: 'Charlotte',
      state: 'NC',
      zip: '28203',
      contractorName: 'Edifice Construction',
      contactEmail: 'permits@edificeconstruction.com',
      contactPhone: '(704) 555-1234',
      estimatedStartDate: '2024-02-15',
      description: '18-story mixed-use tower with retail, office, and 250 residential units. Significant underground parking excavation required.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-clt-002',
      externalPermitId: 'CLT-2024-00923',
      municipalityId: 'int-charlotte',
      projectName: 'NoDa Brewery District Phase 2',
      projectType: 'Commercial',
      status: 'Issued',
      address: '3200 N Davidson St',
      city: 'Charlotte',
      state: 'NC',
      zip: '28205',
      contractorName: 'Barnhill Contracting',
      contactEmail: 'info@barnhill.com',
      contactPhone: '(704) 555-2345',
      estimatedStartDate: '2024-01-20',
      description: 'Commercial brewery and entertainment complex with outdoor amphitheater. Site grading and foundation work.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-clt-003',
      externalPermitId: 'CLT-2024-00945',
      municipalityId: 'int-charlotte',
      projectName: 'Ballantyne Corporate Park Building J',
      projectType: 'Commercial',
      status: 'Approved',
      address: '15000 Ballantyne Commons Pkwy',
      city: 'Charlotte',
      state: 'NC',
      zip: '28277',
      contractorName: 'Balfour Beatty',
      contactEmail: 'charlotte@balfourbeattyus.com',
      contactPhone: '(704) 555-3456',
      estimatedStartDate: '2024-03-01',
      description: '6-story Class A office building with structured parking. Extensive site preparation and grading.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-clt-004',
      externalPermitId: 'CLT-2024-00967',
      municipalityId: 'int-charlotte',
      projectName: 'University City Residential Tower',
      projectType: 'Residential',
      status: 'Under Review',
      address: '8700 JW Clay Blvd',
      city: 'Charlotte',
      state: 'NC',
      zip: '28262',
      contractorName: 'Choate Construction',
      contactEmail: 'bids@choateco.com',
      contactPhone: '(704) 555-4567',
      estimatedStartDate: '2024-04-15',
      description: '12-story student housing development near UNC Charlotte. Foundation and underground utilities work.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-clt-005',
      externalPermitId: 'CLT-2024-00989',
      municipalityId: 'int-charlotte',
      projectName: 'Uptown Hotel & Conference Center',
      projectType: 'Commercial',
      status: 'Approved',
      address: '400 S College St',
      city: 'Charlotte',
      state: 'NC',
      zip: '28202',
      contractorName: 'Holder Construction',
      contactEmail: 'southeast@holderconstruction.com',
      contactPhone: '(704) 555-5678',
      estimatedStartDate: '2024-02-01',
      description: '22-story luxury hotel with 400 rooms and 50,000 SF conference space. Deep foundation excavation.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-clt-006',
      externalPermitId: 'CLT-2024-01012',
      municipalityId: 'int-charlotte',
      projectName: 'Steele Creek Distribution Center',
      projectType: 'Industrial',
      status: 'Issued',
      address: '12500 S Tryon St',
      city: 'Charlotte',
      state: 'NC',
      zip: '28278',
      contractorName: 'Clayco',
      contactEmail: 'charlotte@clayco.com',
      contactPhone: '(704) 555-6789',
      estimatedStartDate: '2024-01-10',
      description: '750,000 SF distribution warehouse. Major site clearing and grading on 65-acre parcel.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-clt-007',
      externalPermitId: 'CLT-2024-01034',
      municipalityId: 'int-charlotte',
      projectName: 'Plaza Midwood Retail Renovation',
      projectType: 'Commercial',
      status: 'Approved',
      address: '1920 Commonwealth Ave',
      city: 'Charlotte',
      state: 'NC',
      zip: '28205',
      contractorName: 'Little Diversified',
      contactEmail: 'projects@littleonline.com',
      contactPhone: '(704) 555-7890',
      estimatedStartDate: '2024-03-15',
      description: 'Renovation of historic retail building with new outdoor plaza. Minor excavation for utilities.',
      estimatedEarthworkFlag: 'unknown',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-clt-008',
      externalPermitId: 'CLT-2024-01056',
      municipalityId: 'int-charlotte',
      projectName: 'Camp North End Phase 3',
      projectType: 'Mixed Use',
      status: 'Issued',
      address: '1824 Statesville Ave',
      city: 'Charlotte',
      state: 'NC',
      zip: '28206',
      contractorName: 'Rodgers Builders',
      contactEmail: 'info@rodgersbuilders.com',
      contactPhone: '(704) 555-8901',
      estimatedStartDate: '2024-01-25',
      description: 'Adaptive reuse and new construction at historic Ford factory site. Site work and new foundations.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
  ];

  // Raleigh Permits
  const raleighPermits: Permit[] = [
    {
      id: 'pmt-ral-001',
      externalPermitId: 'RAL-2024-00456',
      municipalityId: 'int-raleigh',
      projectName: 'Downtown Raleigh Innovation District',
      projectType: 'Mixed Use',
      status: 'Approved',
      address: '300 S Wilmington St',
      city: 'Raleigh',
      state: 'NC',
      zip: '27601',
      contractorName: 'Skanska USA',
      contactEmail: 'raleigh@skanska.com',
      contactPhone: '(919) 555-1234',
      estimatedStartDate: '2024-02-20',
      description: '25-story mixed-use development with tech office space, retail, and residential. Major excavation for 4-level parking deck.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-002',
      externalPermitId: 'RAL-2024-00478',
      municipalityId: 'int-raleigh',
      projectName: 'North Hills Tower III',
      projectType: 'Commercial',
      status: 'Issued',
      address: '4600 Six Forks Rd',
      city: 'Raleigh',
      state: 'NC',
      zip: '27609',
      contractorName: 'Brasfield & Gorrie',
      contactEmail: 'info@brasfieldgorrie.com',
      contactPhone: '(919) 555-2345',
      estimatedStartDate: '2024-01-15',
      description: '16-story Class A office tower in North Hills district. Structured parking and site grading.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-003',
      externalPermitId: 'RAL-2024-00501',
      municipalityId: 'int-raleigh',
      projectName: 'Warehouse District Apartments',
      projectType: 'Residential',
      status: 'Approved',
      address: '500 W Martin St',
      city: 'Raleigh',
      state: 'NC',
      zip: '27603',
      contractorName: 'Clancy & Theys',
      contactEmail: 'raleigh@clancytheys.com',
      contactPhone: '(919) 555-3456',
      estimatedStartDate: '2024-03-10',
      description: '320-unit luxury apartment complex with courtyard amenities. Foundation and underground parking excavation.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-004',
      externalPermitId: 'RAL-2024-00523',
      municipalityId: 'int-raleigh',
      projectName: 'Research Triangle Park Lab Campus',
      projectType: 'Commercial',
      status: 'Issued',
      address: '1000 Park Dr',
      city: 'Raleigh',
      state: 'NC',
      zip: '27709',
      contractorName: 'Turner Construction',
      contactEmail: 'rtp@tcco.com',
      contactPhone: '(919) 555-4567',
      estimatedStartDate: '2024-01-05',
      description: 'Bio-pharma research campus with 3 laboratory buildings. Extensive site work on 40-acre greenfield site.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-005',
      externalPermitId: 'RAL-2024-00545',
      municipalityId: 'int-raleigh',
      projectName: 'Glenwood South Hotel',
      projectType: 'Commercial',
      status: 'Under Review',
      address: '600 Glenwood Ave',
      city: 'Raleigh',
      state: 'NC',
      zip: '27603',
      contractorName: 'Samet Corporation',
      contactEmail: 'projects@sametcorp.com',
      contactPhone: '(919) 555-5678',
      estimatedStartDate: '2024-04-01',
      description: 'Boutique hotel with rooftop restaurant and event space. Foundation work in urban infill location.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-006',
      externalPermitId: 'RAL-2024-00567',
      municipalityId: 'int-raleigh',
      projectName: 'Wake Forest Road Medical Center',
      projectType: 'Infrastructure',
      status: 'Approved',
      address: '3000 Wake Forest Rd',
      city: 'Raleigh',
      state: 'NC',
      zip: '27609',
      contractorName: 'Robins & Morton',
      contactEmail: 'healthcare@robinsmorton.com',
      contactPhone: '(919) 555-6789',
      estimatedStartDate: '2024-02-28',
      description: '150,000 SF outpatient medical facility. Site preparation and utility infrastructure.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-007',
      externalPermitId: 'RAL-2024-00589',
      municipalityId: 'int-raleigh',
      projectName: 'Crabtree Valley Mall Expansion',
      projectType: 'Commercial',
      status: 'Approved',
      address: '4325 Glenwood Ave',
      city: 'Raleigh',
      state: 'NC',
      zip: '27612',
      contractorName: 'JE Dunn Construction',
      contactEmail: 'raleigh@jedunn.com',
      contactPhone: '(919) 555-7890',
      estimatedStartDate: '2024-03-20',
      description: 'Mall expansion with new anchor store and parking structure. Demolition and site preparation.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
    {
      id: 'pmt-ral-008',
      externalPermitId: 'RAL-2024-00612',
      municipalityId: 'int-raleigh',
      projectName: 'Hillsborough Street Student Housing',
      projectType: 'Residential',
      status: 'Issued',
      address: '2800 Hillsborough St',
      city: 'Raleigh',
      state: 'NC',
      zip: '27607',
      contractorName: 'Landmark Properties',
      contactEmail: 'construction@landmarkproperties.com',
      contactPhone: '(919) 555-8901',
      estimatedStartDate: '2024-01-30',
      description: '450-bed student housing near NC State. Foundation and underground utilities.',
      estimatedEarthworkFlag: 'yes',
      syncedAt: new Date().toISOString(),
    },
  ];

  const allPermits = [...charlottePermits, ...raleighPermits];

  // Create some leads from existing permits
  const sampleLeads: Lead[] = [
    {
      id: 'lead-001',
      permitId: 'pmt-clt-001',
      projectName: 'South End Mixed-Use Development',
      contractorName: 'Edifice Construction',
      contactEmail: 'permits@edificeconstruction.com',
      contactPhone: '(704) 555-1234',
      city: 'Charlotte',
      state: 'NC',
      address: '2100 South Blvd',
      description: '18-story mixed-use tower - high volume earthwork opportunity',
      leadOwner: 'Sarah Johnson',
      leadStatus: 'qualified',
      notes: 'Met with project manager. Estimated 45,000 CY export. Requesting quote by Jan 30.',
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-002',
      permitId: 'pmt-clt-006',
      projectName: 'Steele Creek Distribution Center',
      contractorName: 'Clayco',
      contactEmail: 'charlotte@clayco.com',
      contactPhone: '(704) 555-6789',
      city: 'Charlotte',
      state: 'NC',
      address: '12500 S Tryon St',
      description: '750,000 SF distribution warehouse - major grading project',
      leadOwner: 'Mike Chen',
      leadStatus: 'contacted',
      notes: 'Initial call completed. Site visit scheduled for next week. Large volume potential.',
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-003',
      permitId: 'pmt-ral-001',
      projectName: 'Downtown Raleigh Innovation District',
      contractorName: 'Skanska USA',
      contactEmail: 'raleigh@skanska.com',
      contactPhone: '(919) 555-1234',
      city: 'Raleigh',
      state: 'NC',
      address: '300 S Wilmington St',
      description: '25-story development with 4-level parking excavation',
      leadOwner: 'Emily Rodriguez',
      leadStatus: 'new',
      notes: 'High priority - flagship downtown project. Follow up immediately.',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-004',
      permitId: 'pmt-ral-004',
      projectName: 'Research Triangle Park Lab Campus',
      contractorName: 'Turner Construction',
      contactEmail: 'rtp@tcco.com',
      contactPhone: '(919) 555-4567',
      city: 'Raleigh',
      state: 'NC',
      address: '1000 Park Dr',
      description: 'Bio-pharma campus - 40-acre greenfield site work',
      leadOwner: 'David Kim',
      leadStatus: 'qualified',
      notes: 'Pre-qualified for bid. RFP expected Feb 15. Estimated 80,000 CY combined import/export.',
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'lead-005',
      permitId: 'pmt-clt-008',
      projectName: 'Camp North End Phase 3',
      contractorName: 'Rodgers Builders',
      contactEmail: 'info@rodgersbuilders.com',
      contactPhone: '(704) 555-8901',
      city: 'Charlotte',
      state: 'NC',
      address: '1824 Statesville Ave',
      description: 'Adaptive reuse at historic Ford factory - site work and foundations',
      leadOwner: 'Sarah Johnson',
      leadStatus: 'contacted',
      notes: 'Spoke with PM. Need to coordinate with historic preservation requirements.',
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];

  // Save to storage
  municipalityStorage.setIntegrations(integrations);
  municipalityStorage.setPermits(allPermits);
  leadStorage.setLeads(sampleLeads);
}
